spring.application.name=codereviwer
spring.datasource.url=jdbc:mysql://localhost:3306/codereview
spring.datasource.username=root
spring.datasource.password=grkp

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true